Repository TejasNasre/nexmeet, pull requests merged in 2024-10, with the labels that each got.

#21 For Issue #9: Add toasts / pop-ups
  .gitignore
  package.json
  src/app/(event)/add-event/page.tsx
  src/app/(event)/manage-event/page.tsx
  src/app/(event)/register-event/[registerId]/page.tsx
  src/app/(event)/update-event/page.tsx
  src/app/(event-space)/add-event-space/page.tsx
  src/app/(event-space)/explore-event-space/[spaceId]/page.tsx
  src/app/(event-space)/explore-event-space/page.tsx
  src/app/(participants)/participants-details/[id]/page.tsx
  src/app/layout.tsx
  src/components/ui/sonner.tsx
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest

#42 #Add greetings.yml
  .github/workflows/greetings.yml
Labels: gssoc-ext, level 1

#54 Dynamic Form Added
  src/app/(event)/manage-feedback/[eventId]/create/page.tsx
  src/app/(event)/manage-feedback/[eventId]/page.tsx
  src/app/(event)/manage-feedback/[eventId]/responses/[responseId]/page.tsx
  src/app/(event)/manage-feedback/page.tsx
  src/app/forms/[formId]/page.tsx
  src/components/Organisedevent.tsx
  src/components/form-fields/form-fields.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#68 Contact Us page Added
  LEARN.md
  next.config.mjs
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/app/about/page.tsx
  src/app/api/send-contact-notification/route.ts
  src/app/contact/page.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#73 Changed Contributors Page #24
  package-lock.json
  package.json
  src/app/contributors/page.tsx
  src/components/Header.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#70 Implementation For Request Booking At Event Space
  src/app/(event-space)/explore-event-space/[spaceId]/page.tsx
  src/app/(event-space)/explore-event-space/request-booking/page.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#85 Added transition in stats
  package-lock.json
  package.json
  src/app/contributors/page.tsx
  src/components/Hero.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#92 Added approve/reject status in table for organizers
  LEARN.md
  src/app/(participants)/participants-details/[id]/page.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#91 Added contact number validation
  src/app/(event)/register-event/[registerId]/page.tsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#120 Toggle Theme
  .env.example
  src/app/dashboard/page.tsx
  src/app/globals.css
  src/components/Header.tsx
  src/components/Hero.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#119 hover effects
  src/app/contributors/page.tsx
  src/components/EventPageClient.tsx
  src/components/Footer.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#160 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#185 Added Auth and length validation when submitting comment
  src/components/EventPageClient.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#196 [REVAMP]: Event Space Cards || Event space Event Detail page
  src/app/(event-space)/explore-event-space/[spaceId]/page.tsx
  src/app/(event-space)/explore-event-space/page.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#203 Made Participant Details table responsive
  src/app/(participants)/participants-details/[id]/page.tsx
Labels: gssoc-ext, level 1

#176 Revamp the FAQ section
  src/components/Hero.tsx
  src/components/faq.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#195 Event Calendar added
  package-lock.json
  package.json
  src/app/(event)/explore-events/page.tsx
  src/app/api/send-contact-notification/route.ts
  src/app/api/send/route.ts
  src/app/event-calendar/page.tsx
  src/app/globals.css
  src/components/EventPageClient.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#191 Added Super admin page to approve/reject events
  LEARN.md
  src/app/(event)/explore-events/page.tsx
  src/app/admin/page.tsx
  src/app/dashboard/page.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#219 Add community form
  LEARN.md
  src/app/community/page.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#226 Update text contrast for feature card in light mode
  src/app/(event)/explore-events/[eventsId]/page.tsx
  src/app/(event)/explore-events/page.tsx
  src/app/globals.css
  src/components/EventPageClient.tsx
  src/components/FeatureCards.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#223 Added zod validation for all fields in Update Event Page
  src/app/(event)/update-event/page.tsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#180 Update::Implement Form Validation, Dashboard Redirection, and Remove Unused Forms Folder (For Event Feedback)
  src/app/(event)/event-feedback/[eventId]/page.tsx
  src/app/forms/[formId]/page.tsx
  src/components/EventPageClient.tsx
Labels: bug, enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#234 Navbar fix for smaller screens
  src/components/Header.tsx
Labels: bug, good first issue, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#232 Added delete icon in comments box and delete method to remove it from db
  src/components/EventPageClient.tsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#238 feat: "added filter for event status and css fixes"
  src/app/(event)/explore-events/page.tsx
Labels: bug, good first issue, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest
