Repository TejasNasre/nexmeet, pull requests merged in 2024-11, with the labels that each got.

#253 feat: added google maps integration
  .env.example
  package.json
  src/app/(event)/add-event/page.tsx
  src/components/form-fields/LocationAutocomplete.tsx
Labels: gssoc-ext, level 2

#264 Added the Offline Status Indicator
  package-lock.json
  public/offline.html
  public/service-worker.js
  src/app/ClientServiceWorker.tsx
  src/app/dashboard/page.tsx
  src/app/layout.tsx
Labels: enhancement, good first issue, gssoc-ext, level 2

#280 Disable community which are not approved
  src/app/(community)/explore-community/page.tsx
Labels: gssoc-ext, level 1
